// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/28/2025, 12:46:25 AM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/carmelosammarco/Desktop/voice-cloner-main/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/carmelosammarco/Desktop/voice-cloner-main/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/carmelosammarco/Desktop/voice-cloner-main/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/carmelosammarco/Desktop/voice-cloner-main/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/carmelosammarco/Desktop/voice-cloner-main/plugins/**/*.{js,ts,mjs}","/Users/carmelosammarco/Desktop/voice-cloner-main/composables/**/*.{js,ts,mjs}","/Users/carmelosammarco/Desktop/voice-cloner-main/utils/**/*.{js,ts,mjs}","/Users/carmelosammarco/Desktop/voice-cloner-main/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/carmelosammarco/Desktop/voice-cloner-main/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/carmelosammarco/Desktop/voice-cloner-main/app.config.{js,ts,mjs}","/Users/carmelosammarco/Desktop/voice-cloner-main/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;